### ISSUE TITLE
Btnx doesnt start on ubuntu 20.04

### ISSUE THREAD

**Issue by kebook-programacao-1** [cdobrich/btnx#9]
I tried to install btnx on ubuntu 20.04 with Gnome 3.36, during the installation everything went well, but when running '' sudo /etc/init.d/btnx start ",
I get one:
Starting btnx: Button Extension - mouse button rerouter daemon
  btnx: uinput modprobed successfully.
  btnx: Opening config file: / etc / btnx / btnx_config_Default
  btnx: Could not read the config file: No such file or directory
  btnx: Configuration file error.
btnx failed to start (error code 150)

**Comment by cdobrich** [comment]
Hello. Sorry for the delay in reply. Have you tried running btnx-config? It sounds like you have not defined a configuration file yet. The back end service for btnx want to do anything unless you have to find a configuration file.

**Comment by kebook-programacao-1** [comment]
Hello, thanks for the answer, I managed to solve my problem with btnx, but in the end, I ended up replacing it for my purpose, if you are curious, I was trying to do this project, https://github.com/bit-willi/gnome-navigation-between-workspaces-using-mouse-shortcut, thanks anyway!
